<a href="https://colab.research.google.com/github/kwondogeun/green/blob/main/ch3_python_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 라이브러리 불러오기

In [2]:
import numpy as np
print(np.__version__)

1.19.5


In [3]:
temp = np.array([1, 2, 3])
print(type(temp))

<class 'numpy.ndarray'>


## Numpy 배열 생성 및 둘러보기

In [ ]:
data1 = [1,2,3]
data1

[1, 2, 3]

In [ ]:
data2= [1,1,2,2,3,4]
data2

[1, 1, 2, 2, 3, 4]

In [ ]:
my_array1 = np.array(data1)
print(my_array1) 
print(my_array1.shape)

[1 2 3]
(3,)


In [ ]:
my_array2 = np.array(data2)
print(my_array2) 
print(my_array2.shape)

[1 1 2 2 3 4]
(6,)


In [ ]:
my_array3 = np.array([3,6,9,12])
print(my_array3)
print(my_array3.shape)
print(my_array3.dtype)

[ 3  6  9 12]
(4,)
int64


In [ ]:
my_array4 = np.array([[2,4,6],[8,10,12],[14,16,18],[20,22,24]])
my_array4

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [ ]:
my_array4.shape

(4, 3)

In [ ]:
my_array5 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
my_array5.shape

(2, 2, 2)

## Numpy 기본 함수들

### arange

In [ ]:
arrange_array = np.arange(5)
arrange_array

array([0, 1, 2, 3, 4])

In [4]:
arrange_array2 = np.arange(1, 9, 3)
arrange_array2

array([1, 4, 7])

### zeroes, ones

In [ ]:
zeros_array = np.zeros((3,2))
print(zeros_array)
print("Data Type is:", zeros_array.dtype)
print("Data Shape is:", zeros_array.shape)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
Data Type is: float64
Data Shape is: (3, 2)


In [ ]:
ones_array = np.ones((3,4), dtype='int32')
print(ones_array)
print("Data Type is:", ones_array.dtype)
print("Data Shape is:", ones_array.shape)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
Data Type is: int32
Data Shape is: (3, 4)


### reshape


In [ ]:
after_reshape = ones_array.reshape(6,2)
print(after_reshape)
print("Data Shape is:", after_reshape.shape)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
Data Shape is: (6, 2)


In [ ]:
after_reshape = ones_array.reshape(5,3)

ValueError: ignored

In [ ]:
after_reshape = ones_array.reshape(2,3,2)
print(after_reshape)
print("Data Shape is:", after_reshape.shape)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]
Data Shape is: (2, 3, 2)


In [ ]:
after_reshape2= ones_array.reshape(-1,6)
print("reshape(-1,6)? \n")
print(after_reshape2)

reshape(-1,6)? 

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [ ]:
after_reshape3= ones_array.reshape(3,-1)
print("reshape(3, -1)? \n")
print(after_reshape3)
print("Data Shape is:", after_reshape3.shape)

reshape(3, -1)? 

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
Data Shape is: (3, 4)


## Numpy 인덱싱과 슬라이딩

In [ ]:
my_array = np.arange(start=0, stop=4)
print(my_array)

[0 1 2 3]


In [ ]:
print("my_array의 1번째 요소, 즉 위치값이 0인 것은: ", my_array[0])

my_array의 1번째 요소, 즉 위치값이 0인 것은:  0


In [ ]:
print("my_array[0:3]:", my_array[0:3])

my_array[0:3]: [0 1 2]


In [ ]:
my_array2 = np.arange(start=3,stop=30,step=3)
my_array2 = my_array2.reshape(3,3)
my_array2

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [ ]:
my_array2[0:2,0:2]

array([[ 3,  6],
       [12, 15]])

In [ ]:
my_array2[1:3,:]

array([[12, 15, 18],
       [21, 24, 27]])

In [ ]:
my_array2[:,:]

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

## Numpy 정렬

### sort()

In [ ]:
height_arr = np.array([174, 165, 180, 182, 168])
sorted_height_arr = np.sort(height_arr)

print('Height Matrix: ', height_arr)
print('np.sort() Matrix: ', sorted_height_arr)

Height Matrix:  [174 165 180 182 168]
np.sort() Matrix:  [165 168 174 180 182]


In [ ]:
desc_sorted_height_arr = np.sort(height_arr)[::-1]
print('np.sort()[::-1] : ', desc_sorted_height_arr)

np.sort()[::-1] :  [182 180 174 168 165]


### argsort()

In [ ]:
fives = np.array([10, 5, 15, 20])
fives_order = fives.argsort()

print("The original data", fives)
print("The argsort(): ", fives_order)
print("The asending:", fives[fives_order])

The original data [10  5 15 20]
The argsort():  [1 0 2 3]
The asending: [ 5 10 15 20]
